version: '3.8'

services:
  mtf-trading-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mtf-trading-bot
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - config/.env
    volumes:
      - ./config:/app/config:ro  # Read-only config
      - ./logs:/app/logs         # Writable logs
      - ./data:/app/data         # Writable data
    networks:
      - trading-network
    healthcheck:
      test: ["CMD", "python", "-c", "print('Bot is running')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Resource limits (optional but recommended)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  trading-network:
    driver: bridge

# Optional: Add volume for persistent data
volumes:
  trading-data:
    driver: local