# Trading Bot Configuration
# Copy this file and customize for your needs

trading:
  leverage: 5
  base_capital: 100.0
  max_positions: 3
  check_interval: 300  # seconds between checks
  sandbox_mode: true   # IMPORTANT: Set to false only when ready for live trading

strategy:
  rsi:
    period: 14
    buy_threshold: 40.0
    sell_threshold: 60.0
    exit_long: 50.0
    exit_short: 50.0
  
  ema:
    period: 200
  
  adx:
    period: 14
    threshold: 20.0  # Higher = only strong trends
  
  atr:
    period: 14
    multiplier: 2.0
  
  breakout:
    period: 20

# Symbols to monitor (add/remove as needed)
symbols:
  - BTC/USDT
  - ETH/USDT
  - BNB/USDT
  - SOL/USDT
  - ADA/USDT

# Timeframes for multi-timeframe analysis
timeframes:
  - 15m
  - 30m
  - 1h
  - 4h

# Exchange configuration
exchanges:
  binance:
    sandbox: true
    ratelimit: true
    timeout: 30000

# Risk management settings
risk_management:
  max_risk_per_trade: 0.02  # 2% of capital per trade
  stop_loss_pct: 0.02       # 2% stop loss
  take_profit_pct: 0.04     # 4% take profit
  max_daily_trades: 10      # Maximum trades per day
  cooldown_period: 3600     # Seconds between same signals (1 hour)

# Notification settings
notifications:
  telegram:
    enabled: true
    send_startup: true
    send_daily_report: true
    send_error_alerts: true
    max_messages_per_hour: 20
  
  # Future: Add Discord, email, etc.
  discord:
    enabled: false
    webhook_url: ""

# Logging configuration
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  save_to_file: true
  max_file_size: 10  # MB
  backup_count: 5

# Performance tracking
performance:
  track_signals: true
  save_to_database: true
  generate_reports: true
  report_frequency: "daily"  # daily, weekly, monthly